# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_Y <- function(Z_cos, R) {
    .Call('_dincta_compute_Y', PACKAGE = 'dincta', Z_cos, R)
}

scaleRows_dgc <- function(x, p, i, ncol, nrow, thresh) {
    .Call('_dincta_scaleRows_dgc', PACKAGE = 'dincta', x, p, i, ncol, nrow, thresh)
}

